workspace = { members = [
    "gmimc",
    "monolith",
    "poseidon",
    "poseidon2",
    "griffin", "anemoi", "mimc", "rescue_prime", "arion",
] }
[package]
name = "plonky2_bench"
version = "0.1.0"
edition = "2021"
